from storyteller.exbase.splats import ALL_MORTAL_X, ALL_SOLAR_X, ALL_ABYSSAL_X, ALL_INFERNAL_X, ALL_SIDEREAL_X
from storyteller.exbase.splats import ALL_TERRESTRIAL_X, ALL_LIMINAL_X, ALL_LUNAR_X


ALL_SPLATS = ALL_MORTAL_X + ALL_SOLAR_X + ALL_ABYSSAL_X + ALL_INFERNAL_X + ALL_SIDEREAL_X + \
             ALL_TERRESTRIAL_X + ALL_LIMINAL_X + ALL_LUNAR_X