# Generated by Django 4.1.11 on 2023-11-12 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Power",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, null=True)),
                ("family", models.CharField(max_length=12)),
                ("category", models.CharField(max_length=30)),
                ("subcategory", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "unique_together": {("family", "category", "subcategory", "name")},
            },
        ),
        migrations.CreateModel(
            name="SheetInfo",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sheet",
                        serialize=False,
                        to="objects.objectdb",
                    ),
                ),
                ("game", models.CharField(max_length=30)),
                ("template", models.CharField(default="Mortal", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, null=True)),
                ("category", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="StatPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powers",
                        to="storyteller.stat",
                    ),
                ),
            ],
            options={
                "unique_together": {("stat", "name")},
            },
        ),
        migrations.CreateModel(
            name="StatRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, null=True)),
                ("value", models.IntegerField(default=0)),
                ("modules", models.JSONField(default=dict, null=True)),
                ("tags", models.JSONField(default=list, null=True)),
                ("tier", models.SmallIntegerField(default=0)),
                ("context", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="storyteller.sheetinfo",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranks",
                        to="storyteller.stat",
                    ),
                ),
            ],
            options={
                "unique_together": {("sheet", "stat", "context")},
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=30)),
                ("value", models.CharField(max_length=30)),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="storyteller.sheetinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("sheet", "field")},
            },
        ),
        migrations.CreateModel(
            name="StatPowerRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, null=True)),
                ("value", models.IntegerField(default=0)),
                ("modules", models.JSONField(default=dict, null=True)),
                ("tags", models.JSONField(default=list, null=True)),
                ("tier", models.SmallIntegerField(default=0)),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranks",
                        to="storyteller.statpower",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_powers",
                        to="storyteller.sheetinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("sheet", "power")},
            },
        ),
        migrations.CreateModel(
            name="PowerRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, null=True)),
                ("value", models.IntegerField(default=0)),
                ("modules", models.JSONField(default=dict, null=True)),
                ("tags", models.JSONField(default=list, null=True)),
                ("tier", models.SmallIntegerField(default=0)),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranks",
                        to="storyteller.power",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powers",
                        to="storyteller.sheetinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("sheet", "power")},
            },
        ),
        migrations.CreateModel(
            name="CustomPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, null=True)),
                ("value", models.IntegerField(default=0)),
                ("modules", models.JSONField(default=dict, null=True)),
                ("tags", models.JSONField(default=list, null=True)),
                ("tier", models.SmallIntegerField(default=0)),
                ("name", models.CharField(max_length=80)),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customs",
                        to="storyteller.statrank",
                    ),
                ),
            ],
            options={
                "unique_together": {("stat", "name")},
            },
        ),
    ]
