# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0005_auto_20150403_2339'),
        ('storyteller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('control', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CharmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharmSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('sub_id', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='CraftStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='exalted3.Craft')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafts', to='storyteller.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Evocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EvocationArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='EvoCharmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
                ('evo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='exalted3.EvocationArtifact')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
            ],
        ),
        migrations.CreateModel(
            name='StyleCharm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StyleCharmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='exalted3.Style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='storyteller.Persona')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='exalted3.Style')),
            ],
        ),
        migrations.AddField(
            model_name='stylecharm',
            name='charm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='exalted3.StyleCharmName'),
        ),
        migrations.AddField(
            model_name='stylecharm',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_charms', to='storyteller.Persona'),
        ),
        migrations.AddField(
            model_name='evocation',
            name='charm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='exalted3.EvoCharmName'),
        ),
        migrations.AddField(
            model_name='evocation',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evocations', to='storyteller.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='charmset',
            unique_together=set([('category_id', 'sub_id')]),
        ),
        migrations.AddField(
            model_name='charmname',
            name='charmset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='exalted3.CharmSet'),
        ),
        migrations.AddField(
            model_name='charmname',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.ObjectDB'),
        ),
        migrations.AddField(
            model_name='charm',
            name='charm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='exalted3.CharmName'),
        ),
        migrations.AddField(
            model_name='charm',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='storyteller.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='stylestat',
            unique_together=set([('style', 'persona')]),
        ),
        migrations.AlterUniqueTogether(
            name='stylecharmname',
            unique_together=set([('key', 'style')]),
        ),
        migrations.AlterUniqueTogether(
            name='stylecharm',
            unique_together=set([('persona', 'charm')]),
        ),
        migrations.AlterUniqueTogether(
            name='evocharmname',
            unique_together=set([('key', 'evo')]),
        ),
        migrations.AlterUniqueTogether(
            name='evocation',
            unique_together=set([('persona', 'charm')]),
        ),
        migrations.AlterUniqueTogether(
            name='craftstat',
            unique_together=set([('craft', 'persona')]),
        ),
        migrations.AlterUniqueTogether(
            name='charmname',
            unique_together=set([('charmset', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='charm',
            unique_together=set([('persona', 'charm')]),
        ),
    ]
